# docker build -t my-garage:disco -f .\Dockerfile-MyGarage . --progress plain --no-cache
# docker run --env-file debugging.env  -dit --rm -p 80:80 --name my_garage my-garage:disco


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ./Garage ./Garage
COPY ./MyGarage ./MyGarage

WORKDIR /src/MyGarage

RUN dotnet restore MyGarage.csproj
RUN dotnet build MyGarage.csproj -c Release -o /app/build
RUN dotnet publish MyGarage.csproj -c Release -o /app/publish

### Second Stage

FROM nginx:alpine AS final

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Remove default Nginx static assets
RUN rm -rf /usr/share/nginx/html/*

# Copy static assets from the build stage to the Nginx server
COPY --from=build /app/publish/wwwroot /usr/share/nginx/html

# Expose port 80 to the Docker host, so we can access it 
# from the outside.
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
