apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-garage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-garage
  template:
    metadata:
      labels:
        app: the-garage
    spec:
      containers:
      - name: the-garage
        image: ghcr.io/ciroque/the-garage:ce9e34fa
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__AppConfig
          value: "Endpoint=https://mygac171579510454211.azconfig.io;Id=xTm9;Secret=Zu8tQL+1Ig6+iZNzuNxfzbzmlVhfS/eWjg5tUepUtg4="
        livenessProbe:
          httpGet:
            path: "/vehicles"
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: "/vehicles"
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: the-garage-service
spec:
  type: LoadBalancer
  selector:
    app: the-garage
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
