name: Build and Upload Docker Images

on:
  push:
    branches:
      - main
      - git-workflows-images-to-ghcr

jobs:
  build_and_upload_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GARAGE_GHCR_ACCESS }}
     
      - name: Get short commit hash
        id: commit_hash
        run: echo "::set-output name=short_commit_hash::$(echo ${GITHUB_SHA::8})"
           
      - name: Build and push The Garage image 
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-TheGarage
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/the-garage:latest
            ghcr.io/${{ github.repository_owner }}/the-garage:${{ steps.commit_hash.outputs.short_commit_hash }}
      
      - name: Build and push My Garage image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-MyGarage
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/my-garage:latest
            ghcr.io/${{ github.repository_owner }}/my-garage:${{ steps.commit_hash.outputs.short_commit_hash }}
